name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # This is needed if your script is pushing to gh-pages or otherwise committing changes.
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          # Install any npm packages (like mermaid.cli)
          npm install -g mermaid.cli
          # Install Ruby gems needed by the site
          bundle install

      - name: Configure deployment variables
        id: setup
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # If this is a pull request build, set NO_PUSH so we don't try to deploy
          if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then
            echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
            echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF} = refs/heads/* ]]; then
            echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

          # We'll always deploy to gh-pages (adjust if you prefer otherwise)
          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT

      - name: Deploy website
        run: |
          yes | bash bin/deploy --verbose \
            ${{ steps.setup.outputs.NO_PUSH }} \
            --src ${{ steps.setup.outputs.SRC_BRANCH }} \
            --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
